### ISSUE TITLE
Emmet doesn't work with HTML(Angular) code style

### ISSUE THREAD

**Issue by Sokolua** [emmetio/emmet-atom#343]
Tab just do nothing but adding space...

**Comment by leon** [comment]
I have the same issue

**Comment by Galvo87** [comment]
Same issue here..

**Comment by eric-burel** [comment]
Open edit>Open your Keymap
Add these lines :
 'atom-text-editor[data-grammar="text html angular"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'

You can get the grammar full name by opening View>Developper>Toggle Developper Tools and looking for the data-grammar attribute of the atom-text-editor element.

That's a bit tricky, hope it will be set by default in the next versions of Emmet.

**Comment by eric-burel** [comment]
Just sent a pull request to make this the default behaviour

**Comment by Sokolua** [comment]
Thanks=)

**Comment by guywald1** [comment]
Hey, any plans on making this the default behavior?

**Comment by sergeche** [comment]
There’s (broken) PR for this: https://github.com/emmetio/emmet-atom/pull/373
If someone will create a working one, I’ll add it by default

**Comment by eric-burel** [comment]
Hi, I sent this PR a long time ago, and I fixed it recently, are you sure it is still broken ?

**Comment by sergeche** [comment]
Yeah, it tells there are conflicts

**Comment by eric-burel** [comment]
I opened up a new one that works ;)

**Comment by sergeche** [comment]
Done

**Comment by orszaczky** [comment]
FYI I'm still having this issue in atom 1.15.0 x64 / emmet 2.4.3 - editing the keymap manually as suggested above fixed it

**Comment by cdrainxv** [comment]
This was also an issue for me as my angular code is written in TypeScript and occasionally I made use of an embedded template (template: ``). I added this to my keymap:

```
'atom-text-editor[data-grammar="source ts"]:not([mini])':
  'tab': 'emmet:expand-abbreviation-with-tab'
```
