### ISSUE TITLE
wrap element deletes content

### ISSUE THREAD

**Issue by garretwilson** [emmetio/emmet-atom#390]
With Emmet 2.4.1 if I have the sentence:

````html
You must have version 1.8.0 or higher.
````

And I try to wrap (Ctrl+Alt+W) the `1.8.0` with a `<strong>` tag, it deletes part of my content:

````html
You must have version <strong>.8.0</strong> or higher.
````

**Comment by carloschneider** [comment]
+1

**Comment by DrianHillman** [comment]
+1 and similar to Issue #352 

I've seen _**Wrap with Abbreviation**_ do some crazy things altering my code in Atom. 

#### Watch it completely remove the beginning of my selection:

![Emmet messing up](http://recordit.co/znEz5ifM1k.gif)

**Comment by pufflik** [comment]
+1
Confirmed.
Really nightmare. Editing text become huge pain.

**Comment by anthonygrignoux** [comment]
I have had the experience with numbers as the first character of my selection too. I assume it is a Regex problem.

**Comment by Dupanoodle** [comment]
+1
I came here to report the same issue. If a selection starts with a number it can strip it until the next non-numeric character.

**Comment by sergeche** [comment]
Should be fixed in v2.4.3

**Comment by adion** [comment]
I'm running v2.4.3 and can confirm that #352 is at least still an issue.

**Comment by kingluddite** [comment]
In Sublime I highlighted a word and could easily add bold markup using markdown by typing ** and it would surround the word : like this **word**

This is not working in Atom. I can wrap tags but not simple text. Am I missing something?
